import { morePages } from "./seo-more.mjs";

const start = "https://app.marcusfacilities.com/login";

const p = (text) => ({ p: text });
const h2 = (text) => ({ h2: text });
const ul = (items) => ({ ul: items });
const cta = (href, label) => ({ cta: { href, label } });

const firstPages = [
  {
    slug: "job-search-after-layoff",
    title: "Job Search Help After a Layoff | Marcus",
    description:
      "Got laid off? Marcus helps you get back to work with job search, applications, and outreach while you review every step.",
    eyebrow: "Laid off",
    h1: "Got laid off? We'll help you get back to work.",
    lede: ["Need a job? We can help. Don't have time to apply? We can help with your job search."],
    cta: { href: start, label: "Start your job search" },
    questionsTitle: "Questions",
    blocks: [
      h2("The first weeks after a layoff are a second job"),
      p("A layoff notice does not come with extra hours. You still have to find open roles, tailor a résumé, fill out applications, and figure out who to contact. Marcus Reemployment, from Marcus Facilities LLC, does that search work with you."),
      p("You save one role and one location. Marcus looks for recent public postings. You review them. The Application Helper can copy information you already provided onto an application and draft an answer. You review the form. Marcus does not submit it for you by itself."),
      h2("What we help with"),
      ul([
        "Finding jobs that match the role and location you saved",
        "Keeping an Application Passport and résumé ready",
        "Drafting application answers for you to review",
        "Looking for named contacts at the company after you apply",
        "Sending outreach from your own Gmail when you choose to send it",
      ]),
      h2("If you want a person to run the search"),
      p("Starter, Search, and Intensive are for people who want the tools and will submit applications themselves. Do it for you is for people who want a Marcus worker to run the search, applications, and outreach. A person still reviews the work. We do not guarantee a job offer or an interview."),
    ],
    faqs: [
      ["I got laid off. What should I do next?", "Save the role you want and the city you can work in, then start a search while the notice is still fresh. Marcus can queue recent postings so you are not starting from a blank job board."],
      ["Can you help me find a job after a layoff?", "Yes. Marcus helps with the search, the applications, and the follow-up. You review jobs and drafts before they are used."],
      ["Can someone apply to jobs for me?", "On Do it for you, a Marcus worker can help complete applications by hand. The software does not submit an application on its own. On the other plans, you submit on the employer site after Marcus helps you prepare."],
    ],
  },
  {
    slug: "job-search-while-on-a-pip",
    title: "Job Search While on a PIP | Marcus",
    description: "Got put on a PIP? Start a private job search now. Marcus helps you look for the next job while you are still employed.",
    eyebrow: "On a PIP",
    h1: "Got put on a PIP? It may be time to start looking.",
    lede: [
      "A PIP, or Performance Improvement Plan, does **not always mean you are getting fired**. But it is a pretty good reason to make sure you have a Plan B.",
      "You do not have to quit your job. You do not have to panic. And you definitely do not have to announce on LinkedIn that you are looking.",
      "You can quietly start your job search now while you still have a paycheck.",
    ],
    cta: { href: start, label: "Start your job search" },
    questionsTitle: "Questions about being on a PIP",
    blocks: [
      h2("On a PIP? Give yourself another option."),
      p("Maybe you finish the PIP and everything works out. Great."),
      p("Maybe you decide you do not even want to stay there anymore. Also fair."),
      p("Or maybe your employer has already made up its mind. Unfortunately, we do not have a crystal ball for that one. What you **can** control is whether you are prepared."),
      p("Marcus can help you look for jobs while you are still working. Tell us the type of job and location you want, and we can help you find openings, prepare applications, find people at the company to contact, and keep your search moving."),
      p("You decide which jobs you want to go after."),
      h2("You already have a job. Now you have a PIP too. Who has time for another full-time job?"),
      p("Being on a PIP can mean more meetings, more emails, more notes, more check-ins, and a lot more stress."),
      p("Then somebody tells you:"),
      p("**“You should probably start applying for jobs too.”**"),
      p("Great. Just what you needed."),
      p("Job searching can take hours. You have to find openings, read job descriptions, update your resume, fill out applications, answer the same questions again and again, find recruiters, and follow up."),
      p("Marcus helps with the busy work."),
      p("You keep doing your actual job. We help make the job search easier to manage."),
      h2("You can search without your employer knowing."),
      p("You do not need to quit before you start looking."),
      p("You can search for another job while you are still employed. Marcus uses the job title, location, and other preferences you give us to help find opportunities."),
      p("You choose what you want to apply for."),
      p("Our Application Helper can also help you fill out applications faster, but it will not secretly hit **Submit** while you are sleeping. You stay in control."),
    ],
    faqs: [
      ["Should I look for a job while on a PIP?", ["It may be a smart idea.", "A PIP does not always lead to getting fired, but it does mean you should think about your next step.", "You can keep doing your current job while quietly looking at other options. If everything works out at your current company, great. If it does not, you already started your search."]],
      ["What should I do after getting put on a PIP?", ["First, read the PIP carefully and understand what your employer is asking you to improve.", "Keep copies of important documents and emails. If you have questions about your legal rights, talk to an employment lawyer.", "Then think about your backup plan.", "If you would rather not wait to see what happens, Marcus can help you start looking for your next job now."]],
      ["Can I get fired after a PIP?", ["Yes. Some people are fired after a PIP.", "Other people complete the PIP and keep their jobs.", "Marcus cannot tell you what your employer will decide. What we can do is help you prepare so that losing your job is not also the day you have to start your job search from zero."]],
      ["I’m on a PIP. Should I start looking for another job?", ["If you want another option, yes.", "Looking does not mean you have to leave.", "You can apply, interview, and see what is out there while you are still employed. You might even find something better."]],
      ["Will my employer know I am looking for another job?", ["Marcus does not contact your current employer just because you start a search.", "You choose the jobs you want to pursue and the people you want to contact.", "Of course, no job search can promise complete secrecy, so be careful about what you post publicly and who you tell."]],
      ["Can Marcus help me apply while I am still working?", ["Yes.", "Marcus is built for people who do not have hours every night to spend searching and applying.", "We can help with job searches, applications, company contacts, outreach, and follow-up so you can keep working while also preparing for what comes next."]],
      ["What if I survive the PIP?", ["Then you have options.", "You can stay where you are, stop your search, or keep looking if you found something better.", "Starting a job search does not mean you have decided to leave. It simply means you are not putting your entire future in someone else's hands."]],
    ],
    after: [
      h2("You do not have to wait until you lose your job."),
      p("If you are on a PIP, worried about getting fired, unhappy at work, or just want a backup plan, you can start looking now."),
      p("**Keep the paycheck. Start the search. See what else is out there.**"),
      cta(start, "Start your job search"),
    ],
  },
  {
    slug: "find-a-second-job",
    title: "Find a Second Job | Marcus",
    description: "Need a second job or more money? Marcus helps you find the next opportunity when you do not have time to apply.",
    eyebrow: "Need a second job",
    h1: "Need a second job or more money? Let’s find your next opportunity.",
    lede: [
      "Maybe your paycheck is not stretching like it used to.",
      "Maybe you want extra income, a better-paying job, or something you can do on the side.",
      "Or maybe you like your current job just fine. You just need **more money**.",
      "You do not have to quit your job to start looking for another one. Marcus can help you search while you keep the paycheck you already have.",
    ],
    cta: { href: start, label: "Find a second job" },
    questionsTitle: "Questions about finding a second job",
    blocks: [
      h2("You already have one job. Finding another should not become Job #2."),
      p("You work all day. Then you come home and somehow you are supposed to spend another three hours searching job boards, filling out applications, updating your resume, and answering:"),
      p("**“Why do you want to work here?”**"),
      p("For the 14th time."),
      p("No thanks."),
      p("Marcus helps with the time-consuming parts of the job search."),
      p("Tell us what type of job you want and where you want to work. We can help find openings, prepare applications, find people at the company to contact, and keep your search moving."),
      p("You review the jobs and decide which ones are worth your time."),
      h2("Looking for extra money? Start with what actually fits your life."),
      p("A second job only helps if you can actually work it."),
      p("Maybe you need:"),
      ul(["Evening work", "Weekend work", "Remote work", "Part-time work", "A better-paying full-time job", "A second source of income", "A job with a better schedule"]),
      p("Your search should fit your life, not make your life harder."),
      p("Marcus helps you focus on the type of work you actually want instead of scrolling through hundreds of jobs that make no sense for you."),
      h2("We help with the applications too."),
      p("Finding a good job is only half the battle."),
      p("Then comes the application."),
      p("Name. Address. Work history. Education. Skills."),
      p("And somehow they still want your resume after making you type your entire resume into the application."),
      p("We know."),
      p("Our **Application Helper** can use information you already gave Marcus to help fill out applications faster and draft answers to application questions."),
      p("You review everything before it goes to the employer."),
      p("The Application Helper will not secretly hit **Submit** while you are sleeping."),
      p("You are still in control."),
      h2("Don't have time to apply? We can help with that too."),
      p("If you want more hands-on help, our **Do It for You** service can take more of the job-search work off your plate."),
      p("A Marcus worker can help search for jobs and prepare applications using the information you provide."),
      p("Think of it like getting an extra set of hands for your job search."),
      p("You handle the interviews."),
      p("We help with the work it takes to get there."),
    ],
    faqs: [
      ["Can you help me find a second job?", ["Yes.", "You do not have to be unemployed to use Marcus.", "Tell us what kind of job you want and where you can work. Marcus can help you search while you keep the job you already have."]],
      ["I need more money. Can Marcus help me find extra work?", ["Yes.", "Marcus can help you look for another job, a better-paying job, or work that gives you another source of income.", "We cannot promise a certain salary, schedule, interview, or job offer. But we can help you find opportunities and keep applying."]],
      ["Can someone help me apply for jobs because I don't have time?", ["Yes. That is one of the main reasons Marcus exists.", "You already have a job, family, school, errands, sleep and hopefully some kind of life.", "Marcus can help with job searches, applications, company contacts, and follow-up so you do not have to spend every free hour doing it yourself."]],
      ["Do I have to quit my current job first?", ["No.", "Please keep your paycheck.", "You can search, apply, and interview for other jobs while you are still working.", "If you find something better, then you can decide what you want to do next."]],
      ["Can I use Marcus to find a better-paying job instead of a second job?", ["Absolutely.", "Maybe you do not actually want two jobs.", "Maybe you just need **one job that pays enough**.", "Marcus can help you search for a better-paying opportunity while you continue working at your current job."]],
      ["Can Marcus find part-time or weekend jobs?", ["Marcus can search based on the type of work and location you choose. If you are looking for part-time, evening, weekend, remote, or other flexible work, make that part of your search.", "Job schedules and availability depend on what employers are hiring for at the time."]],
      ["Will my current employer know I am searching?", ["Marcus does not contact your current employer just because you start a job search.", "You decide which jobs you want to pursue and who you want to contact.", "As with any private job search, be careful about what you post publicly and who you tell."]],
      ["Can Marcus guarantee I will make more money?", ["No.", "We would love that superpower, but employers still control salaries and hiring decisions.", "Marcus can help you find opportunities that match what you are looking for, prepare stronger applications, and keep your search moving."]],
    ],
    after: [
      h2("Your free time should still be free sometimes."),
      p("You already have a job."),
      p("Your job search does not need to take over every night and weekend too."),
      p("**Keep working. Keep earning. Let us help you look for what’s next.**"),
      cta(start, "Find a second job"),
    ],
  },
];

export const pages = [...firstPages, ...morePages];
