const start = "https://app.marcusfacilities.com/login";
const mail = "mailto:sales@marcusfacilities.com";
const sales = "**[sales@marcusfacilities.com](mailto:sales@marcusfacilities.com)**";

const p = (text) => ({ p: text });
const h2 = (text) => ({ h2: text });
const ul = (items) => ({ ul: items });
const cta = (href, label) => ({ cta: { href, label } });

export const morePages = [
  {
    slug: "job-search-help-for-veterans",
    title: "Job Search Help for Veterans | Marcus",
    description: "Job search help for veterans who need civilian roles, application help, and follow-up without spending every night on job boards.",
    eyebrow: "Veterans",
    h1: "Job search help for veterans",
    lede: [
      "Leaving the military and looking for a civilian job? We can help with the search, applications, employer contacts, and follow-up.",
      "You already have experience. The hard part is sometimes getting a civilian employer to understand what that experience actually means.",
      "Marcus can help.",
    ],
    cta: { href: start, label: "Start your veteran job search" },
    questionsTitle: "Questions about job search help for veterans",
    blocks: [
      h2("Your military experience counts. Your resume just needs to explain it."),
      p("You may know exactly what you did in the military."),
      p("A civilian hiring manager may not."),
      p("Military titles, duties, systems, and skills do not always translate neatly into a civilian resume or job application."),
      p("And unfortunately, most applications do not have a box that says:"),
      p("**“Trust me. I know how to do this job.”**"),
      p("So we help you explain it."),
      p("Marcus can use the resume and career information you provide to help you find civilian jobs that fit your background, prepare application answers, improve how your experience is explained, and find people at the company you may want to contact."),
      p("You still review the work and decide what gets sent."),
      h2("You have already filled out enough paperwork."),
      p("Finding a job can mean hours of:"),
      ul([
        "Searching job boards",
        "Reading job descriptions",
        "Updating your resume",
        "Filling out applications",
        "Typing the same work history again and again",
        "Looking for recruiters or hiring managers",
        "Following up after you apply",
      ]),
      p("You probably did enough paperwork during your service."),
      p("Marcus helps take some of the job-search work off your plate."),
      p("Tell us the kind of job you want and where you want to work. We can help you find opportunities and keep the search moving."),
      h2("Not sure what civilian jobs fit your military experience?"),
      p("That is normal."),
      p("Your next job does not have to have the same title you had in the military."),
      p("Skills like leadership, operations, logistics, maintenance, security, project management, technology, training, planning, and working under pressure can transfer into many civilian careers."),
      p("Marcus can help you look at jobs based on what you know how to do not just the title that happened to be on your uniform."),
      h2("You stay in control."),
      p("Marcus is here to help with your job search, not take control of it."),
      p("You choose what kind of work you want."),
      p("You review the jobs."),
      p("You review your application information."),
      p("Our **Application Helper** can help you fill out applications faster, but it does not secretly click **Submit** while you are sleeping."),
      p("If you want more hands-on help, our **Do It for You** service can provide a Marcus worker to help with more of the search and application work."),
      h2("Veterans may be able to get Marcus through a sponsor."),
      p("You may not have to pay for Marcus yourself."),
      p("A veterans organization, nonprofit, workforce program, employer, foundation, or other sponsor may be able to pay for your job-search support."),
      p("You still get your own Marcus account and control your job search."),
      p("The sponsor helps cover the cost."),
      p(`If your organization wants to sponsor veterans, contact ${sales}.`),
      h2("Marcus is not the VA and we are not trying to be."),
      p("Marcus is a private job-search service."),
      p("We are not the Department of Veterans Affairs, a government veterans program, or a Veterans' Employment Representative."),
      p("We also do not replace VA benefits, government employment programs, legal advice, or other veteran services you may qualify for."),
      p("Think of Marcus as **extra hands for the job search**."),
      p("We help with finding jobs, applications, employer contacts, outreach, and follow-up."),
    ],
    faqs: [
      ["Do you help veterans find civilian jobs?", ["Yes.", "Marcus can help veterans find jobs that match their skills and experience, prepare applications, contact employers, and stay organized during the search.", "You do not need to already know the perfect civilian job title before you start."]],
      ["Can you help translate my military experience for civilian jobs?", ["Yes.", "We can help you explain military experience in clearer civilian language for resumes and applications.", "The goal is not to change what you did. It is to make sure an employer actually understands it."]],
      ["What if I don't know what kind of job I should apply for?", ["That is okay.", "We can help you look at your experience and think about civilian roles where those skills may transfer.", "Sometimes the right civilian job has a completely different title from the job you had in the military."]],
      ["Can a veterans program pay for Marcus?", ["Yes.", "A veterans organization, nonprofit, workforce program, employer, or other sponsor may be able to pay for a veteran's Marcus service.", `Organizations interested in sponsoring veterans can contact ${sales}.`]],
      ["Do I have to pay if a program sponsors me?", ["If an organization fully sponsors your service, that organization pays Marcus for the covered service instead of you.", "The details may depend on the program sponsoring you."]],
      ["Will Marcus submit applications without me knowing?", ["No.", "Our Application Helper does not automatically submit applications.", "You review the information and submit the application yourself.", "With **Do It for You**, a Marcus worker can provide more hands-on application help, but the work is still connected to your job search and the information you provide."]],
      ["Can you help me contact recruiters and hiring managers?", ["Yes.", "Marcus can help identify recruiters, hiring managers, or other people at companies where you are interested in working.", "We can also help prepare a short message so your entire strategy is not:", "**Apply → refresh email → hope.**"]],
      ["Do you guarantee that I'll get a job?", ["No.", "No honest job-search service can promise that an employer will hire you.", "We can help you find opportunities, prepare applications, reach people at companies, follow up, and keep your search moving.", "You handle the interviews.", "The employer makes the final hiring decision."]],
    ],
    after: [
      h2("You served. You have skills. Let's help employers understand them."),
      p("Starting a civilian job search can feel like learning a whole new system."),
      p("You do not have to figure out every part of it by yourself."),
      p("**You bring the experience. We help with the search.**"),
      cta(start, "Start your veteran job search"),
    ],
  },
  {
    slug: "outplacement-services",
    title: "Outplacement Services for Companies | Marcus",
    description: "Outplacement and reemployment services for companies going through layoffs, WARN notices, reductions in force, and workforce changes.",
    eyebrow: "Employers",
    h1: "Outplacement services that actually help people look for work",
    lede: [
      "Layoffs are hard enough.",
      "If your company has to let people go, Marcus can help them with what comes next: finding jobs, preparing applications, reaching out to employers, and keeping their job search moving.",
      "Your company pays for the support. Your employees get the help.",
    ],
    cta: { href: mail, label: "Talk to us about outplacement" },
    questionsTitle: "Questions about outplacement services",
    blocks: [
      h2("Don't just hand people a list of resources and wish them luck."),
      p("Traditional outplacement can sometimes mean a resume review, a few videos, and a long list of websites someone could have Googled themselves."),
      p("That is not very helpful when someone just lost their paycheck."),
      p("Marcus gives affected employees hands-on job-search support."),
      p("We can help them:"),
      ul([
        "Find jobs that match what they are looking for",
        "Prepare resumes and applications",
        "Fill out applications faster",
        "Find recruiters and hiring managers",
        "Prepare professional outreach",
        "Follow up after applying",
        "Stay organized during the search",
        "Prepare for what comes next",
      ]),
      p("Employees still control their own job search and review their information."),
      p("We help with the work."),
      h2("Your company pays. The employee gets the support."),
      p("When a company uses Marcus for outplacement, the company sponsors the affected employees."),
      p("Marcus is not recruiting workers **for your company**."),
      p("We are helping the people leaving your company find their **next** company."),
      p("There is no placement fee when someone gets hired somewhere else."),
      p("You pay for the job-search support. We help your former employees use it."),
      p("Simple."),
      h2("WARN notice? Mass layoff? Reduction in force?"),
      p("If you already know employees will be affected, you do not have to wait until their last day to offer help."),
      p("Marcus can support workers during:"),
      ul([
        "WARN notices",
        "Mass layoffs",
        "Reductions in force (RIFs)",
        "Department closures",
        "Plant or office closures",
        "Restructuring",
        "Position eliminations",
        "Other workforce changes",
      ]),
      p("Employees may be able to start looking while they are still receiving a paycheck."),
      p("That can make the next step a little less scary."),
      h2("Give people more than a severance check."),
      p("Money helps."),
      p("So does having someone help you figure out what happens Monday morning."),
      p("Marcus can give affected employees access to job-search tools and support based on the level of help your company wants to provide."),
      p("That can include job searches, application help, employer contact research, outreach, and more hands-on support."),
      p("Because **“Good luck out there”** is not really an outplacement plan."),
      h2("What can employees get?"),
      p("Depending on the program your company chooses, employees can receive help with:"),
      ul([
        "Job searches based on their role and location",
        "Resume updates",
        "Job applications",
        "Our Application Helper for faster applications",
        "Application question drafts",
        "Hiring manager and recruiter research",
        "Outreach and follow-up",
        "More hands-on job-search help through **Do It for You**",
      ]),
      p("Each employee gets their own account and manages their own job search."),
      h2("Can the company see what employees are doing?"),
      p("Companies can receive progress information for the workers they sponsor."),
      p("We do **not** simply hand the company every private detail from an employee's Application Passport."),
      p("The goal is to let the sponsor understand whether the program is being used and how the job search is moving without turning someone's private job search into an open book."),
    ],
    faqs: [
      ["Do you offer outplacement services for companies?", ["Yes.", "Marcus provides outplacement and reemployment support for companies dealing with layoffs, WARN notices, reductions in force, closures, and other workforce changes.", "Your company sponsors the service, and affected employees receive job-search help."]],
      ["What is outplacement?", ["Outplacement is help a company provides to employees who are losing their jobs.", "Instead of saying:", "**“Sorry about the layoff. Here is your final paycheck. Good luck.”**", "the company gives employees support finding their next opportunity.", "Marcus focuses on the actual job search: finding jobs, preparing applications, reaching employers, and keeping the search moving."]],
      ["Is Marcus a reverse recruiting company?", ["For an individual job seeker, you may hear the term **reverse recruiting**.", "A normal recruiter works for the company trying to hire someone.", "A reverse recruiter works for the person trying to get hired.", "When a company pays for that help for employees affected by a layoff, it is usually called **outplacement** or **reemployment support**.", "Different name. Same basic goal: help someone find their next job."]],
      ["Do you help employees after a WARN notice?", ["Yes.", "Companies facing a WARN notice or planned mass layoff can sponsor Marcus for affected employees.", "Starting the job search before someone's final day can give them more time to find their next opportunity."]],
      ["Can employees start looking before their layoff date?", ["Yes.", "If the company has already told employees their positions are ending, they may be able to begin their job searches before their last day.", "Marcus can help them start looking instead of waiting until the paycheck stops."]],
      ["Do you charge a placement fee when someone gets hired?", ["No.", "Marcus does not charge the employee's next employer a recruiting or placement fee.", "The sponsoring company pays Marcus for the outplacement service.", "If an employee gets hired somewhere else, congratulations to them. There is no surprise bill waiting for the new employer."]],
      ["Does Marcus guarantee everyone will find a job?", ["No.", "No outplacement company can control an employer's hiring decision.", "What Marcus can do is give employees tools and support to find opportunities, prepare applications, reach the right people, follow up, and keep moving.", "We help with the search.", "The next employer makes the hiring decision."]],
      ["Can Marcus support a large layoff?", ["Potentially, yes.", "The size of the program, number of affected employees, level of support, timeline, and reporting needs can be discussed with Marcus before the program begins.", `Contact ${sales} and tell us what is happening.`]],
      ["Can we sponsor only some employees?", ["Potentially, yes.", "A company may want different levels of support based on the situation, employee group, location, or program.", "We can discuss what makes sense for your workforce."]],
      ["What does the company receive?", ["The company can receive agreed-upon program and progress reporting for sponsored employees.", "The employee keeps their own job-search account and private application information.", "We want companies to know the program is actually helping without making employees feel like someone is standing over their shoulder watching every application."]],
    ],
    after: [
      h2("If people have to leave, help them land somewhere else."),
      p("You may not be able to prevent every layoff."),
      p("You **can** decide what kind of support people receive on the way out."),
      p("**Your company handles the transition. Marcus helps them handle what comes next.**"),
      cta(mail, "Talk to us about outplacement"),
    ],
  },
  {
    slug: "layoff-warn-outplacement",
    title: "Layoff and WARN Outplacement Services | Marcus",
    description: "Reemployment and job-search support for workers named in a layoff or WARN notice. For employers, HR, and workforce partners.",
    eyebrow: "Layoffs / WARN",
    h1: "Layoff and WARN outplacement services",
    lede: [
      "Planning a layoff or filing a WARN notice?",
      "Marcus can help your employees with what comes next.",
      "We provide job-search and reemployment support to help affected workers find jobs, prepare applications, contact employers, and start moving toward their next opportunity.",
    ],
    cta: { href: mail, label: "Ask about WARN and layoff support" },
    questionsTitle: "Questions about WARN notices and layoffs",
    blocks: [
      h2("A layoff is hard. Finding the next job should not be harder."),
      p("When someone finds out their job is ending, they suddenly have a new job:"),
      p("**Finding a job.**"),
      p("And unfortunately, that job does not come with a paycheck."),
      p("Marcus helps affected employees with the time-consuming parts of the search."),
      p("We can help with:"),
      ul([
        "Finding job openings",
        "Resume and application help",
        "Filling out applications faster",
        "Finding recruiters and hiring managers",
        "Preparing outreach",
        "Following up after applications",
        "Keeping the job search organized",
        "More hands-on help when needed",
      ]),
      p("The employee still controls their search and reviews their information."),
      p("We help with the work."),
      h2("Don't wait until the last day."),
      p("If your company already knows a layoff is coming, employees may be able to start their job search before their final day."),
      p("That gives them more time to look while they still have income."),
      p("A WARN notice, mass layoff, or reduction in force is already stressful."),
      p("Waiting until someone's last paycheck to say, **“Okay, now start looking,”** usually does not make things easier."),
      p("Marcus can help people start earlier."),
      h2("What is a WARN notice?"),
      p("A WARN notice is connected to certain large layoffs or business closings."),
      p("For Marcus, the important part is simple:"),
      p("**People are about to lose their jobs, and they may need help finding the next one.**"),
      p("Marcus is not a government agency and we do not provide legal advice about WARN laws."),
      p("We provide the job-search support that can come after the notice."),
      h2("Your company can pay for the support."),
      p("Companies can sponsor Marcus for employees affected by a layoff."),
      p("The employee gets their own account and job-search support."),
      p("Your company pays for the service."),
      p("There is no placement fee charged to the employee's next employer when they get hired."),
      p("You are paying to help people get back to work."),
      h2("Workforce programs can sponsor workers too."),
      p("Marcus can also work with workforce programs, nonprofits, community organizations, and other groups helping people after layoffs."),
      p("A company and a workforce partner may also be able to work together to support affected employees."),
      p("The goal is simple:"),
      p("**Help people spend less time figuring out how to job search and more time actually job searching.**"),
    ],
    faqs: [
      ["Do you help people after a WARN notice or mass layoff?", ["Yes.", "Marcus can help affected employees find jobs, prepare applications, contact recruiters and hiring managers, and follow up.", "A company, workforce program, nonprofit, or other organization may sponsor the service for affected workers."]],
      ["Do you offer outplacement after a reduction in force?", ["Yes.", "Marcus can provide outplacement and reemployment support after:", "WARN notices, mass layoffs, reductions in force (RIFs), department closures, office or plant closings, restructuring, and position cuts.", "Different words. Same problem: people need help finding what comes next."]],
      ["Can employees start their job search before their last day?", ["Yes.", "If employees already know their jobs are ending, they do not necessarily have to wait until their final day to start looking.", "Starting earlier gives them more time to find opportunities, apply, interview, and prepare for the next step."]],
      ["What does Marcus actually do for laid-off employees?", ["Depending on the program, Marcus can help employees:", "Search for jobs, improve resumes, prepare applications, fill out applications faster, find company contacts, write outreach, follow up after applying, and stay organized during the search.", "We do not just give someone a list of job websites and say:", "**“Good luck. You've got this.”**", "We help with the actual work."]],
      ["Is Marcus a government Rapid Response program?", ["No.", "Marcus is a private job-search and reemployment service.", "We can work alongside employers, workforce programs, nonprofits, and other organizations, but we are not a government Rapid Response agency."]],
      ["Does Marcus guarantee employees will get another job?", ["No.", "We cannot control who an employer decides to hire.", "What we can do is help affected workers find opportunities, submit stronger applications, reach the right people, follow up, and keep their searches moving."]],
      ["Does the employee have to pay?", ["If the company or another organization fully sponsors the employee, the sponsor pays Marcus for the covered service.", "The employee receives the job-search support without paying for that sponsored service themselves."]],
      ["Can Marcus help with a large group of laid-off employees?", ["Potentially, yes.", "Tell us how many employees are affected, where they are located, when the layoff is happening, and what level of help you want to provide.", "We can talk through what makes sense for your group."]],
      ["My company filed a WARN notice. How do we get started?", [`Email ${sales}.`, "Tell us your company name, about how many employees are affected, where the employees are located, the expected layoff date, and what kind of support you want to provide.", "We can take it from there."]],
    ],
    after: [
      h2("A WARN notice tells people their job is ending. Help them figure out what comes next."),
      p("You may not be able to stop the layoff."),
      p("But you can give people more than a notice, a severance check, and a handshake on the way out."),
      p("**Your company handles the layoff. Marcus helps your people start the next search.**"),
      cta(mail, "Ask about WARN and layoff support"),
    ],
  },
  {
    slug: "workforce-development-services",
    title: "Reemployment and Workforce Development Services | Marcus",
    description: "Help dislocated workers, laid-off employees, veterans, and other job seekers get back to work faster.",
    eyebrow: "Workforce programs",
    h1: "Reemployment and workforce development services",
    lede: [
      "Helping someone find work takes more than telling them to check Indeed.",
      "Marcus can help workforce programs, nonprofits, schools, community groups, and other organizations give job seekers hands-on help with finding jobs, preparing applications, reaching employers, and staying on track.",
      "Your program sponsors the service.",
      "The job seeker gets the help.",
    ],
    cta: { href: mail, label: "Talk with us about workforce services" },
    questionsTitle: "Questions about workforce development services",
    blocks: [
      h2("Your program already helps people. We help with the job-search work."),
      p("Workforce programs serve people dealing with all kinds of barriers."),
      p("Some were laid off."),
      p("Some are veterans moving into civilian work."),
      p("Some have been unemployed for months."),
      p("Some are working but need a better-paying job."),
      p("Some are raising families, going to school, dealing with health issues, or handling life while also being told:"),
      p("**“You should apply to more jobs.”**"),
      p("Easier said than done."),
      p("Marcus can work alongside your program to help participants with the time-consuming parts of finding employment."),
      h2("What can Marcus help participants with?"),
      p("Depending on the program, participants can get help with:"),
      ul([
        "Finding jobs that match their goals",
        "Resume help",
        "Job applications",
        "Filling out applications faster",
        "Application question drafts",
        "Finding recruiters and hiring managers",
        "Professional outreach",
        "Following up after applications",
        "Keeping their job search organized",
        "More hands-on support when needed",
      ]),
      p("The participant still controls their job search."),
      p("Marcus helps them do the work."),
      h2("Give people more than another job board."),
      p("Most people already know jobs are online."),
      p("That is usually not the problem."),
      p("The problem is finding the **right** jobs, filling out applications over and over, figuring out who to contact, following up, and doing all of it long enough to get results."),
      p("A list of websites is useful."),
      p("Someone helping you actually use them is better."),
      p("Marcus is built to help with that part."),
      h2("Programs can sponsor job seekers."),
      p("A workforce program, nonprofit, school, community group, employer, foundation, or other organization may be able to sponsor Marcus for the people it serves."),
      p("The participant gets their own account."),
      p("The sponsor pays for the covered service."),
      p("That can help programs offer more support without asking every job seeker to pay for it themselves."),
      h2("Participants still have privacy."),
      p("A sponsor may receive agreed-upon information about program progress."),
      p("That might include things like whether someone is using the service, how their search is moving, or other program results."),
      p("The participant's private Application Passport is not simply handed over to the sponsor."),
      p("We want programs to see whether their support is working without making the participant feel like someone is reading over their shoulder."),
      h2("Marcus can support different kinds of job seekers."),
      p("Programs may use Marcus to support:"),
      ul([
        "Dislocated workers",
        "People affected by layoffs",
        "Veterans",
        "Career changers",
        "Single parents",
        "Students and recent graduates",
        "People returning to work",
        "People looking for better-paying jobs",
        "People who have been unemployed for a long time",
        "Other job seekers who need more support",
      ]),
      p("Different people may need different levels of help."),
      p("That is kind of the point."),
      h2("Marcus does not replace your workforce program."),
      p("We are not trying to take over your program."),
      p("Marcus can be one more tool your team uses to help participants move toward employment."),
      p("Your program may already provide coaching, training, benefits, case management, certifications, transportation help, or other services."),
      p("Marcus focuses on the job search."),
      p("Think of us as **extra hands for the employment part**."),
    ],
    faqs: [
      ["Do you work with workforce development programs?", ["Yes.", "Marcus can work with workforce programs and other organizations that help people find employment.", "A program can sponsor participants, give them access to Marcus, and receive agreed-upon progress information.", "Each participant keeps their own account."]],
      ["Do you help dislocated workers?", ["Yes.", "Workers who lost their jobs because of layoffs, closures, downsizing, or other workforce changes can use Marcus for job-search and reemployment help.", "We can help them look for jobs, prepare applications, contact employers, and keep moving toward their next role."]],
      ["Can a workforce board sponsor job seekers?", ["Potentially, yes.", "Workforce boards and partner organizations can contact Marcus to discuss sponsoring job seekers or groups of participants.", "The exact setup may depend on the program, funding source, number of participants, and type of support needed.", `Contact ${sales} to talk through it.`]],
      ["Can nonprofits sponsor people too?", ["Yes.", "A nonprofit, foundation, community organization, school, employer, or other sponsor may be able to pay for Marcus services for the people they serve.", "That allows the participant to receive job-search support without paying for the sponsored service themselves."]],
      ["Do you work with veterans programs?", ["Yes.", "Marcus can support veterans looking for civilian employment and can work with organizations that serve veterans.", "We can help with job searches, applications, resumes, employer contacts, and follow-up."]],
      ["Do you replace the local workforce center?", ["No.", "Marcus is not a government workforce agency or local workforce center.", "We are an added job-search service that a workforce program can choose to offer.", "Your program keeps doing what it does.", "We help with the part that involves:", "**Find job → apply → contact employer → follow up → repeat.**"]],
      ["Can Marcus work with a group of participants?", ["Potentially, yes.", "Tell us how many people you serve, who the program is designed to help, where participants are located, what kind of job-search help they need, how long the program runs, and what progress information your organization needs.", "We can discuss a setup that makes sense for the program."]],
      ["Can we see whether participants are actually using Marcus?", ["Yes.", "A sponsor can receive agreed-upon progress information for the participants it sponsors.", "We can discuss what information your program needs while still protecting private candidate information."]],
      ["Does Marcus guarantee that participants will get jobs?", ["No.", "Employers still make their own hiring decisions.", "Marcus can help participants find opportunities, prepare applications, reach employers, follow up, and keep working their search.", "We cannot promise the final hiring decision."]],
    ],
    after: [
      h2("You help people get back to work. We can help with the workload."),
      p("Your team may already be helping people with training, benefits, transportation, coaching, and everything else that comes with getting someone's life moving again."),
      p("You do not have to add **“spend three hours applying to jobs for every participant”** to that list."),
      p("**Your program supports the person. Marcus helps support the job search.**"),
      cta(mail, "Talk with us about workforce services"),
    ],
  },
  {
    slug: "sponsored-job-search-services",
    title: "Sponsored Job Search Services | Marcus",
    description: "A parent, nonprofit, school, workforce program, or employer can pay for someone's job search. The job seeker keeps their own account.",
    eyebrow: "Sponsors / nonprofits",
    h1: "Sponsored job search services",
    lede: [
      "Want to help someone find work?",
      "You can sponsor their job search.",
      "A parent, friend, family member, church, nonprofit, school, workforce program, employer, foundation, or any other person or group can pay for Marcus services for someone else.",
      "The sponsor pays.",
      "The job seeker gets the help.",
    ],
    cta: { href: mail, label: "Sponsor a job seeker" },
    questionsTitle: "Questions about sponsoring a job seeker",
    blocks: [
      h2("Anyone can be a sponsor"),
      p("You do not need to run a nonprofit or workforce program to help someone."),
      p("Maybe your adult child is struggling to find work."),
      p("Maybe a friend was laid off."),
      p("Maybe someone at your church needs help getting back on their feet."),
      p("Maybe you know a single parent who does not have three extra hours every night to search and apply."),
      p("Maybe your company wants to help employees after a layoff."),
      p("If you want to pay for someone's Marcus service, you may be able to sponsor them."),
      p("Simple as that."),
      h2("What does the job seeker get?"),
      p("Depending on the plan, Marcus can help the sponsored job seeker with:"),
      ul([
        "Finding jobs",
        "Resume help",
        "Job applications",
        "Filling out applications faster",
        "Application question drafts",
        "Finding recruiters and hiring managers",
        "Professional outreach",
        "Follow-up after applying",
        "Keeping the job search organized",
        "More hands-on help when needed",
      ]),
      p("The job seeker still controls their search."),
      p("We are helping them find work, not taking over their life."),
      h2("The sponsor pays. The job seeker keeps their own account."),
      p("Sponsoring someone does **not** mean sharing a password."),
      p("Please do not do that. Nobody needs that kind of chaos."),
      p("The job seeker gets their own Marcus login and account."),
      p("The sponsor pays for the service."),
      p("If the sponsor has access to progress reporting, they may be able to see agreed-upon updates about how the search is going."),
      h2("What can a sponsor see?"),
      p("Depending on the sponsorship setup, a sponsor may see basic progress such as:"),
      ul([
        "Whether the Case is active",
        "Roles or employers connected to the search",
        "Application activity",
        "Application dates",
        "Search progress",
        "Interview or outcome information",
        "Other agreed-upon program results",
      ]),
      p("Sponsors do not automatically get access to every private detail the job seeker provides."),
      p("For example, private information stored in the job seeker's Application Passport is not simply handed over because someone else paid the bill."),
      p("Paying for someone's job search does not mean buying access to their entire life story."),
      h2("Who can sponsor a job seeker?"),
      p("Almost anyone."),
      p("Sponsors may include:"),
      ul([
        "Parents",
        "Family members",
        "Friends",
        "Churches",
        "Community groups",
        "Nonprofits",
        "Foundations",
        "Workforce programs",
        "Schools",
        "Colleges",
        "Training programs",
        "Employers",
        "Veterans organizations",
        "Reentry programs",
        "Domestic violence support organizations",
        "Other people or groups that want to help someone find work",
      ]),
      p("You do not need to fit into a special category."),
      p("If you want to help someone with their job search, talk to us."),
      h2("Why sponsor someone?"),
      p("Sometimes the person who needs the most help is also the person who can least afford it."),
      p("Someone may be unemployed."),
      p("Someone may have just been laid off."),
      p("Someone may be raising children alone."),
      p("Someone may be leaving a difficult situation."),
      p("Someone may be a veteran moving into civilian work."),
      p("Someone may simply be overwhelmed and need extra help."),
      p("A sponsor can step in and say:"),
      p("**“I will cover this. You focus on finding your next job.”**"),
      p("That can make a big difference."),
    ],
    faqs: [
      ["Can an individual sponsor someone?", ["Yes.", "You do not have to be a company or nonprofit.", "A parent, family member, friend, or other person can sponsor someone else's Marcus service."]],
      ["Can a nonprofit or workforce program sponsor job seekers?", ["Yes.", "Organizations can sponsor one person or potentially a group of people, depending on the program.", "Each job seeker gets their own account."]],
      ["Can an employer sponsor someone?", ["Yes.", "An employer may sponsor Marcus for employees affected by layoffs, WARN notices, reductions in force, or other workforce changes.", "Companies may also use Marcus as part of an outplacement or reemployment program."]],
      ["Can a church sponsor someone?", ["Yes.", "A church, faith-based group, community organization, or other group can sponsor someone who needs job-search help."]],
      ["Can I sponsor a family member?", ["Yes.", "If your child, parent, sibling, spouse, or another family member needs help finding work, you can pay for their Marcus service.", "They still get their own account and control their own job search."]],
      ["Can I sponsor a single parent?", ["Yes.", "A sponsor can help a single parent or anyone else who may not have the time or money to run a full job search alone."]],
      ["Can I sponsor a veteran?", ["Yes.", "Individuals, veterans groups, nonprofits, employers, and other organizations may sponsor veterans who need help finding civilian work."]],
      ["Does the sponsor control the job search?", ["No.", "The job seeker still decides what type of work they want, which jobs they want to pursue, and what information they want to use.", "The sponsor is helping pay for the service.", "They are not choosing the person's career for them."]],
      ["Does the sponsor get the job seeker's password?", ["No.", "Each person gets their own login.", "A sponsor should never need the job seeker's password."]],
      ["What private information can the sponsor see?", ["Sponsors do not automatically receive access to the job seeker's private Application Passport or every application detail.", "If progress reporting is part of the sponsorship, Marcus can provide agreed-upon updates while still protecting private candidate information."]],
      ["Can I sponsor someone anonymously?", ["Possibly.", "If you want to pay for someone's service without being involved in their job search, contact Marcus and explain what you are trying to do.", "We can talk through the best setup."]],
      ["Can I pay for more than one person?", ["Yes.", "If you want to sponsor several people, a family, a group, or a larger program, contact Marcus so we can discuss the setup."]],
    ],
    after: [
      h2("Sometimes the best way to help someone is to help them get back to work."),
      p("You do not have to write their resume."),
      p("You do not have to search job boards at midnight."),
      p("You do not have to fill out applications for them."),
      p("You can help pay for the support."),
      p("**You help cover the cost. Marcus helps with the job search.**"),
      cta(mail, "Sponsor a job seeker"),
    ],
  },
  {
    slug: "faq",
    title: "Job Search FAQ | Marcus",
    description: "Answers to common searches: laid off, on a PIP, second job, veterans, outplacement, WARN notices, and sponsored job search.",
    eyebrow: "FAQ",
    h1: "Questions",
    lede: [],
    cta: null,
    questionsTitle: "",
    blocks: [],
    faqs: [
      ["Can someone apply to jobs for me?", ["Yes. With our **Do It for You** service, a Marcus worker can help search for jobs and complete applications using the information you give us. You review the information before it is submitted. With our help, you should be able to get some interviews. Our job is to handle the applications and you handle the interviews.", "Our software does not secretly apply to jobs without you knowing. You stay in control of your job search."]],
      ["I got laid off. What should I do next?", ["Start your job search as soon as you can. Update your resume, decide what type of job you want next, and begin looking while your experience is still fresh.", "Marcus can help you find jobs, prepare applications, reach out to hiring managers, and keep your search moving so you do not have to figure everything out alone."]],
      ["Can you help me find a job after a layoff?", ["Yes. Marcus can help you search for jobs that match your experience, prepare applications, find people at the company to contact, and follow up after you apply.", "Getting laid off is stressful enough. Your job search does not have to become another full-time job."]],
      ["I’m on a PIP. Should I start looking for another job?", ["It may be a good idea to start looking before you actually need a new job.", "Being placed on a Performance Improvement Plan, or PIP, does not always mean you will lose your job, but it gives you a reason to prepare. Marcus can help you quietly start your job search while you are still employed."]],
      ["Can someone help me apply for jobs because I don’t have time?", ["Yes. That is one of the main reasons Marcus exists.", "Searching for jobs, filling out the same information over and over, finding hiring managers, and following up can take hours. You have a life, and we don't. Marcus helps with that work so you can spend more time working, taking care of your family, going to school, or simply living your life."]],
      ["Can you help me find a second job?", ["Yes. You do not have to be unemployed to use Marcus.", "If you need more income, want a better job, or simply want another option, Marcus can help you search while you keep the job you already have."]],
      ["What is a reverse recruiter?", ["A regular recruiter usually works for the company that is hiring.", "A **reverse recruiter works for the job seeker**.", "Instead of helping a company find workers, Marcus helps you find jobs, prepare applications, contact the right people, and manage your job search."]],
      ["What is a job application service?", ["A job application service helps take some of the work out of applying for jobs.", "Marcus can help find openings, prepare application information, improve your resume, find company contacts, and help with follow-up. You still review your information and stay in control of what is submitted."]],
      ["Do you help veterans find jobs?", ["Yes. Marcus can help veterans search for civilian jobs, prepare applications, contact employers, and stay organized during the job search.", "We know that moving into a new career can feel overwhelming, especially when you are already dealing with work, family, health, or other responsibilities. Our goal is to make the job search easier to manage."]],
      ["Do you help single parents find jobs?", ["Yes. Marcus is built for people who may not have hours every day to search and apply for jobs.", "If you are working, raising children, going to school, or handling other responsibilities, we can help take some of the job-search work off your plate.", "Some job seekers may also receive Marcus services through a nonprofit, workforce program, employer, or other sponsor."]],
      ["Do you help people after a WARN notice or mass layoff?", ["Yes.", "If you received a WARN notice or your company announced layoffs, you do not have to wait until your last day of work to start looking.", "Marcus can help affected workers begin their job search early, find openings, prepare applications, and reach out to employers. Companies can also provide Marcus as an outplacement service for employees affected by layoffs."]],
      ["Do you offer outplacement services for companies?", ["Yes. Marcus can help companies support employees during layoffs, WARN notices, reductions in force, and other workforce changes.", "Instead of simply giving employees a list of resources, Marcus can help them actually search for jobs, prepare applications, find employer contacts, and move toward their next opportunity."]],
      ["Do you work with workforce development programs?", ["Yes. Marcus can work with workforce development programs, nonprofits, schools, community organizations, and other groups that help people find employment.", "Organizations can sponsor job seekers and give them access to job-search help without requiring the job seeker to pay for the service themselves."]],
      ["Can nonprofits or workforce programs sponsor job seekers?", ["Yes. A nonprofit, workforce program, company, school, foundation, or other organization may be able to pay for a job seeker's Marcus services.", "The job seeker still has their own account and job search. The sponsor helps cover the cost so the person can receive more support."]],
      ["Can my employer pay for Marcus after a layoff?", ["Yes. Companies can use Marcus as an outplacement or reemployment service for workers affected by layoffs.", "The company pays for the service, and the employee receives help with their job search, applications, employer outreach, and next steps."]],
      ["What if I have not searched for a job in years?", ["That is okay.", "A lot may have changed since your last job search. Marcus can help you figure out what jobs fit your background, update how you present your experience, find openings, and start applying again.", "You do not need to know where to begin before you begin."]],
      ["Can Marcus guarantee that I will get a job?", ["No. No honest job-search service can promise that an employer will hire you.", "What Marcus can do is help you put in the work: find opportunities, prepare stronger applications, reach the right people, follow up, and keep your search moving.", "The employer makes the final hiring decision."]],
      ["Does Marcus automatically submit job applications for me?", ["No. The **Application Helper** helps make applications faster by using information you already provided, but it does not secretly click Submit for you.", "You can review the application before it goes to the employer."]],
      ["Can Marcus help me contact hiring managers and recruiters?", ["Yes. Marcus can help find people who may be connected to the role you applied for, such as recruiters, hiring managers, or other employees.", "We can also help prepare a short professional message so you are not just applying and hoping someone notices your resume."]],
      ["Why should I use Marcus instead of applying by myself?", ["You can absolutely search and apply by yourself.", "Marcus is for people who want help with the time-consuming parts of the job search. Instead of spending hours finding jobs, filling out applications, searching for contacts, and keeping track of follow-ups, you can use Marcus to make the process easier and faster.", "Think of us as extra hands for your job search."]],
    ],
  },
];
